parameters:
  # ...

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: true

  PhpClassFuzz\:
    resource: '../*'
    exclude: '../{Config,Application,Exception,Collection,Argument,Di,Fuzz/Result,Corpus}/*'

  PhpClassFuzz\Command\:
    resource: '../Command/*'
    tags: [ 'console.command' ]

  PhpClassFuzz\Mutator\Type\String\:
    resource: '../Mutator/Type/String/*'
    tags: [ 'fuzz.mutator.string' ]

  Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'


